name: Push Success Check

on:
  push:  # Trigger this action on every push
    branches:
      - main  # or use 'master' or any branch you want

jobs:
  say-success:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show success message
        run: echo "✅ Push was successful!"
