name: Push Success Check

on:
  push:
    branches:
      - main  

jobs:
  say-success:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show success message
        run: echo "Push was successful!"